export const initialUsers = [
  {
    username: 'admin',
    password: '12345',
    email: 'admin@test.fi',
    fullname: 'Administrator',
    isAdmin: true,
  },
  {
    username: 'user',
    password: '00000',
    email: 'user@test.fi',
    fullname: 'Normal User',
    isAdmin: false,
  },
  {
    username: 'special',
    password: '99999',
    email: 'special@admin.fi',
    fullname: 'Special User',
    isAdmin: false,
  },
];

export const initialPhotos = [
  {
    mainUrl: 'https://main.url',
    thumbUrl: 'https://thumb.url',
    filename: 'filename.jpg',
    thumbFilename: 'thumbFilename.jpg',
    originalFilename: 'originalFilename.jpg',
    width: 150,
    height: 100,
    name: 'Photo name',
    location: 'Photo location',
    description: 'Photo description',
    tags: ['landscape', 'animals'],
    album: null,
    user: '',
  },
  {
    mainUrl: 'https://main.url2',
    thumbUrl: 'https://thumb.url2',
    filename: 'filename2.jpg',
    thumbFilename: 'thumbFilename2.jpg',
    originalFilename: 'originalFilename2.jpg',
    width: 140,
    height: 90,
    name: 'Photo name2',
    location: 'Photo location2',
    description: 'Photo description2',
    tags: ['landscape', 'night', 'forrest'],
    album: null,
    user: '',
  },
  {
    mainUrl: 'https://main.url3',
    thumbUrl: 'https://thumb.url3',
    filename: 'filename3.jpg',
    thumbFilename: 'thumbFilename3.jpg',
    originalFilename: 'originalFilename3.jpg',
    width: 160,
    height: 110,
    name: 'Photo name3',
    location: 'Photo location3',
    description: 'Photo description3',
    tags: ['animals', 'cat'],
    album: null,
    user: '',
  },
  {
    mainUrl: 'https://main.url4',
    thumbUrl: 'https://thumb.url4',
    filename: 'filename4.jpg',
    thumbFilename: 'thumbFilename4.jpg',
    originalFilename: 'originalFilename4.jpg',
    width: 100,
    height: 150,
    name: 'Photo name4',
    location: 'Photo location4',
    description: 'Photo description4',
    tags: ['portrait', 'photomodel'],
    album: null,
    user: '',
  },
  {
    mainUrl: 'https://main.url5',
    thumbUrl: 'https://thumb.url5',
    filename: 'filename5.jpg',
    thumbFilename: 'thumbFilename5.jpg',
    originalFilename: 'originalFilename5.jpg',
    width: 90,
    height: 140,
    name: 'Photo name5',
    location: 'Photo location5',
    description: 'Photo description5',
    tags: [''],
    album: null,
    user: '',
  },
];

export const initialAlbums = [
  {
    name: 'Album1',
    description: 'Description1',
    photos: [],
    user: '',
  },
  {
    name: 'Album2',
    description: 'Description2',
    photos: [],
    user: '',
  },
  {
    name: 'Album3',
    description: 'Description3',
    photos: [],
    user: '',
  },
];
